### ISSUE TITLE
how can I get primary key when I executed insert sql ?

### ISSUE THREAD

**Issue by lizhou828** [Cito/DBUtils#15]
how can I get primary key when I executed insert sql ?

**Comment by Cito** [comment]
That depends on the underlying database and db api. In PyGreSQL classic, the [insert()](http://www.pygresql.org/contents/pg/db_wrapper.html#pg.DB.insert) method puts them into the dictionary, and the [query()](http://www.pygresql.org/contents/pg/connection.html#pg.Connection.query) method returns the oid. In PostgreSQL you can also add a RETURNING clause to the insert statement and then fetch the row as usual.
