### ISSUE TITLE
set timeout condition on connection

### ISSUE THREAD

**Issue by vamkaxifa** [Cito/DBUtils#16]
Hi there, I have a project which used to access oracle database using DBUtils with cx_Oracle. There are two kinds of operation one is for QUERY and the other one is for IUD(INSERT、UPDATE、DELETE). 
Now I want to specify the number of milliseconds which I want to wait for each round-trip to the database.
As [issue277 from cx_Oracle](https://github.com/oracle/python-cx_Oracle/issues/277), I can make use of the [call timeout](https://cx-oracle.readthedocs.io/en/latest/connection.html#Connection.callTimeout) feature available until I update client to  18.3. 
After I update my client to 18.3 and twist code into :
```
pool = PooledDB(cx_Oracle,
                                                        threaded=True,
                                                        user="user_name",
                                                        password="password",
                                                        dsn="xxx.xxx.xxx.xxx/xxx",
                                                        mincached=min_cached,
                                                        maxcached=max_cached,
                                                        maxshared=max_shard,
                                                        maxconnections=max_con)
conn = db_pool.connection()
conn.callTimeout = time_out  # time_out=0.000000000000000000000001
cursor = conn.cursor()
try:
      cursor.execute(sql, values)
except Exception as e:   # expceting timeout error 
      logger.error(str(e), traceback.format_exc())
```
It seems `callTimeout` feature is useless, it does't take effect. 

I'm wondering dose DBUtils support [call timeout](https://cx-oracle.readthedocs.io/en/latest/connection.html#Connection.callTimeout) feature ？if yes then how?

**Comment by Cito** [comment]
Hi @vamkaxifa 

I did not look deeply into this, but I guess the reason why this doesn't work is the following: DBUtils does proxy the readable attributes (even non-standard ones) to the underlying steady connection, but it does not proxy writable attributes (settable properties) since no such attributes exist in DB API 2 and common drivers. I would need to add that functionality for non-standard attributes such as `callTimeout`.

In the meantime, you can set the attribute on the underlying steady connection manually. Something like `conn._con.callTimeout = ...` should probably work. Please try it out and give feedback.

I will look into that more closely when I have more time.

**Comment by vamkaxifa** [comment]
Hi @Cito 
I tried `conn._con.callTimeout=...` as below:
```
pool = PooledDB(cx_Oracle,
                                                        threaded=True,
                                                        user="user_name",
                                                        password="password",
                                                        dsn="xxx.xxx.xxx.xxx/xxx",
                                                        mincached=min_cached,
                                                        maxcached=max_cached,
                                                        maxshared=max_shard,
                                                        maxconnections=max_con)
conn = db_pool.connection()
conn._con.callTimeout = time_out  # time_out=0.000000000000000000000001
cursor = conn.cursor()
try:
      cursor.execute(sql, values)
except Exception as e:   # expceting timeout error 
      logger.error(str(e), traceback.format_exc())
```
It turns out that I haven't caught timeout exception.  It seems callTimeout feature  doesn't work as before.

**Comment by Cito** [comment]
@vamkaxifa thanks for the feedback. Sorry, I forgot that you need to reach through 2 levels (the shared connection holds a steady connection, which holds the actual cx_Oracle connection). Therefore you need to set `conn._con._con.callTimeout=... `

**Comment by vamkaxifa** [comment]
@Cito Thanks for your guidance. After I set 
``` 
      time_out =0.000000000000000000000000000000000000000001
      conn._con._con.callTimeout= time_out 
````
and run it on `instant client 12.2  it throws exception `cx_Oracle.DatabaseError: DPI-1050: Oracle Client library is at version 12.2 but version 18.1 or higher is needed`,  then I update my client to 18.1, the `DPI-1050`exception  disappeared. For now, I think DBUtils do pass `callTimeout`attributes to cx_Oracle. 

But the call time out exception did not appear either.  I'll give feedback to cx_Oracle. 
For reference, If you are interested， the request timestamp is `2019-03-14 14:48:53.844018`, response timestamp is `2019-03-14 14:48:53.844799` (time formate is %Y-%m-%d %H:%M:%S.%f),  comparing with `time_out`,it is short enough to trigger call time out exception.

**Comment by Cito** [comment]
You should try it out with a normal cx_Oracle connection first without using DBUtils and see if that works. Also, you must be aware of the consequences in DBUtils where connections are shared - the next thread that is using the same connection will also have the same timeout. If you don't want that, you must use dedicated connections and reset the timeout again before closing the connection.

**Comment by vamkaxifa** [comment]
Thanks a lot! I'll be careful with using this feature.  Since my problem has been solved, I'll close this issue, thank you again!
