### ISSUE TITLE
thread_pool use PooledDB InvalidConnection 

### ISSUE THREAD

**Issue by QscvGYU** [Cito/DBUtils#20]
def __getattr__(self, name):
        """Proxy all members of the class."""
        if self._con:
            return getattr(self._con, name)
        else:
            raise InvalidConnection

name = 'commit'

**Comment by Cito** [comment]
Looks like you commit on a shared or dedicated connection that has been closed.

Please send a complete reproducible test case, explain what you expect and what happened instead.
