### ISSUE TITLE
AttributeError using cause by missing __exit__ function 

### ISSUE THREAD

**Issue by leofiore** [Cito/DBUtils#6]
Using DBUtils.PooledDB on python3.5, tested with PyGreSQL, psycopg2cffi, and mysqlclient.

If i try to define a cursor using the `with` statement, the library causes an exception. For example:

    pool = PooledDB(pgdb, 100, [connection params])

    with pool.cursor() as cur:
          cur.execute("select 1")

this code generates an `AttributeError: __exit__` Exception. This happens using any database connector, so is not related to the underlying implementation of the external libraries. The solution is to rewrite the code as 

    pool = PooledDB(pgdb, 100, [connection params])

    cur = pool.cursor():
    cur.execute("select 1")
    cur.close()

but this makes the refactoring of pre-existent code not so immediate.

**Comment by Cito** [comment]
Right. DBUtils and DBAPI 2 were developed when there were no context managers in Python. But after many database drivers are providing them now for connections and cursors, we should really add support in DBUtils, too.

**Comment by Cito** [comment]
This has been added in version 1.3 now.
